ALTER TABLE app_settings ADD COLUMN auto_submit INTEGER NOT NULL DEFAULT 0;
ALTER TABLE app_settings ADD COLUMN auto_next INTEGER NOT NULL DEFAULT 0;
ALTER TABLE app_settings ADD COLUMN arrow_keys INTEGER NOT NULL DEFAULT 1;
